src/Entity/Traits/FileUploadTrait.php
<?php

declare(strict_types=1);

namespace App\Entity\Traits;

use Doctrine\ORM\Mapping as ORM;

trait FileUploadTrait
{
    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $fileFn = null;

    public function getFileFn(): ?string
    {
        return $this->fileFn;
    }

    public function getUploadFileFn(): ?string
    {
        return $this->fileFn ? (self::getUploadDir().'/'.$this->fileFn) : null;
    }

    public function getFullFileFn(): ?string
    {
        return $this->fileFn ? (self::getBasePath().'/'.$this->fileFn) : null;
    }

    public function setFileFn(?string $file): self
    {
        $this->fileFn = $file;

        return $this;
    }

    public static function getClassName(): string
    {
        $ar = explode('\\', self::class);

        return array_pop($ar);
    }

    public static function getUploadDir(): string
    {
        return '/public/upload/'.self::getClassName();
    }

    public static function getBasePath(): string
    {
        return '/upload/'.self::getClassName();
    }
}

src/Controller/WebsiteController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Interface\TranslationInterface as Locale;
use App\Factory\ContactMailer;
use App\Form\MailType;
use App\Repository\ArticleRepository;
use App\Repository\RealizationRepository;
use App\Repository\SliderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Asset\Exception\AssetNotFoundException;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route('/{_locale}/')]
class WebsiteController extends AbstractController
{
    #[Route(name: 'homepage')]
    public function index(
        SliderRepository $sliderRepository,
        ArticleRepository $articleRepository,
        RealizationRepository $realizationRepository,
    ): Response {
        return $this->render('website/homepage.html.twig', [
            'sliders' => $sliderRepository->findAll(),
            'articles' => $articleRepository->findAll(),
            'realizations' => $realizationRepository->findAll(),
        ]);
    }

    #[Route([Locale::POLISH => 'kontakt', Locale::ENGLISH => 'contact'], name: 'contact')]
    public function contact(
        Request $request,
        TranslatorInterface $translator,
        ContactMailer $contactMailer,
        MailerInterface $mailer,
    ): Response {
        $form = $this->createForm(MailType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            try {
                $data = $form->getData();

                if (5 === (int) $data['number']) {
                    $mailer->send($contactMailer->build($data['email'], $data['message']));

                    $this->addFlash('success', $translator->trans('The form has been sent.'));
                } else {
                    $this->addFlash('danger', $translator->trans('Math operation is not valid.'));
                }
            } catch (TransportExceptionInterface) {
                $this->addFlash('danger', $translator->trans('An error has occurred.'));
            }
        }

        return $this->render('website/contact.html.twig', ['form' => $form->createView()]);
    }

    #[Route([Locale::POLISH => 'o-mnie', Locale::ENGLISH => 'about-me'], name: 'about me')]
    public function aboutMe(Request $request): Response
    {
        return match ($request->getLocale()) {
            Locale::POLISH => $this->render('website/about-me.html.twig'),
            default => $this->render('website/not-access.html.twig'),
        };
    }

    #[Route('curriculum-vitae', name: 'curriculum vitae')]
    public function curriculumVitae(Request $request): Response
    {
        return $this->render('website/curriculum-vitae.html.twig', [
            'CVPath' => sprintf('upload/CV_%s.pdf', strtoupper($request->getLocale())),
        ]);
    }

    #[Route('file/{fileName}', name: 'file')]
    public function getFile(string $fileName, string $projectDir): BinaryFileResponse
    {
        $path = $projectDir.'/public/upload/'.$fileName;

        return file_exists($path)
            ? new BinaryFileResponse($path)
            : throw new AssetNotFoundException('File '.$fileName.' is not exists.');
    }
}

templates/website/about-me.html.twig
{% extends 'website/base.html.twig' %}

{% block content %}
    <div class="p-5">
        <h1 class="text-center">{{ "About me"|trans }}</h1>
        <div class="row">
            <div class="col-lg-10 col-md-9 col-sm-12">
                <p class="text-justify">
                    Jestem team leaderem trzy osobowego zespołu, w którego skład wchodzi <a href="#lusia">Lusia</a> i
                    <a href="#odi">Odi</a>. Razem tworzymy aplikacje internetowe. Wytwarzam monolity, systemy api oraz
                    mikroserwisy. Głównie korzystam z frameworka symfony, ale również miałem okazję pracować nad
                    laravelem. Z technologii frontendowych tworzę responsywne strony w oparciu o bibliotekę boostrap
                    oraz tworzę interaktywne komponenty w oparciu o bilbiotekę jQuery lub framework VUE. Czasami nawet
                    napiszę jakiś unit lub behat test.
                </p>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-12 text-end">
                <img src="{{ asset('build/img/meet.png') }}" alt="Odi meet" class="w-100"/>
            </div>

            <hr class="my-2">

            <div class="col-lg-2 col-md-4 col-sm-12" id="lusia">
                <img src="{{ asset('build/img/Odi.jpeg') }}" class="rounded-circle w-100" alt="Odi"/>
            </div>

            <div class="col-lg-10 col-md-8 col-sm-12" id="odi">
                <p class="text-justify">
                    <a href="#odi">Odi</a> zajmuje się projektowaniem baz danych oraz pisaniem skomplikowanych zapytań
                    SQL. Miał przyjemność pracować przy relacyjnych bazach danych takich jak MySQL, MariaDB, PostgreSQL
                    jak i przy nierelacyjnej bazie NoSQL. Robi zaawansowane wyszukiwarki na elasticsearchu oraz korzysta
                    z silnika redis do zapisywania cache. Lubi wygrzewać się na słońcu 🌞.
                </p>
            </div>

            <hr class="my-2">

            <div class="col-lg-10 col-md-8 col-sm-12">
                <p class="text-justify">
                    <a href="#lusia">Lusia</a> zajmuje się devopsowaniem, stawia VPS'y, tworzy dockerfile do lokalnych
                    środowisk oraz pisze skrypty shell na systemy linux. Jej ulubiony system to linux ubuntu mate. Jest
                    odpowiedzialna również za system kontroli wersji. Korzysta z najpopularniejszego systemu git, tworzy
                    pull request'y i robi code review. Zajmuje się całą architekturą aplikacji, w wolnych
                    chwilach degustuje parówki 🍗.
                </p>
            </div>

            <div class="col-lg-2 col-md-4 col-sm-12 text-end" id="lusia">
                <img src="{{ asset('build/img/Lusia.jpeg') }}" class="rounded-circle w-100" alt="Lusia"/>
            </div>
        </div>
    </div>
{% endblock %}

templates/website/base.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('app') }}
{% endblock %}

{% block body %}
    <div class="website">
        {{ include('component/header.html.twig') }}
        {{ include('component/alerts.html.twig') }}
        <main class="container p-0">
            {% block content %}{% endblock %}
        </main>
        {{ include('component/footer.html.twig') }}
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>const route_phone_number = "{{ path('phone_number')|escape('js') }}";</script>
    {{ encore_entry_script_tags('app') }}
{% endblock %}

templates/website/contact.html.twig
{% extends 'website/base.html.twig' %}

{% block content %}
    <div class="homepage p-5">
        <h1 class="text-center">{{ "Contact"|trans }}</h1>
        <article class="article container py-2">
            <h2 class="mb-3">{{ "Contact"|trans }}</h2>
            <i class='fa fa-phone mr-2 icon-con'></i> <span class="ml-2 phone-number">{{ "show"|trans }}</span><br>
            <i class='fa fa-envelope mr-2 icon-con'></i> <span class="ml-2"><a href="mailto:{{ email }}">{{ email }}</a></span>
            <h2 class="mt-5">{{ "Contact form"|trans }}</h2>
            {{ form(form) }}
        </article>
    </div>

    <section>
        <iframe class="map" src="{{ googleMap }}"></iframe>
    </section>
{% endblock %}

templates/website/curriculum-vitae.html.twig
{% extends 'website/base.html.twig' %}

{% block content %}
    <embed src="{{ asset(CVPath) }}" type="application/pdf" width="100%" height="1200px" />
{% endblock %}

templates/website/homepage.html.twig
{% extends 'website/base.html.twig' %}

{% set locale = app.request.locale %}

{% block content %}
    <div id="carousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            {% for key,slider in sliders %}
                <button type="button" data-bs-target="#carousel" data-bs-slide-to="{{ key }}"
                        class="{{ loop.first?'active' }}" aria-current="true" aria-label="Slide {{ key }}"></button>
            {% endfor %}
        </div>
        <div class="carousel-inner">
            {% for key,slider in sliders %}
                <div class="carousel-item {{ loop.first?'active' }}" data-bs-interval="{{ (key+1)*10000 }}">
                    <img src="{{ asset(slider.fullFileFn) }}" class="d-block w-100" alt="{{ slider.translate(locale).title }}">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>{{ slider.translate(locale).title }}</h5>
                    </div>
                </div>
            {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <div class="homepage p-5">
        {% set i = 0 %}
        {% for article in articles %}
            <article class="article p-2 my-4 row {{ i%2 == 0 ? 'slide-left' : 'slide-right' }}" id="article_{{ i }}">
                <div class="col-md-9">
                    {{ i == 0 ? '<h1>' : '<h2>' }}{{ article.translate(locale).title }}{{ i == 0 ? '</h1>' : '</h2>' }}
                    <div class="text-shadow mb-2">{{ article.translate(locale).description|raw }}</div>
                </div>
                <div class="col-md-3">
                    <img src="{{ asset(article.fullFileFn) }}" alt="{{ article.translate(locale).title }}">
                </div>
            </article>
            {% set i = i + 1 %}
        {% endfor %}
        <article class="article p-2 my-4 {{ i%2 == 0 ? 'slide-left' : 'slide-right' }} row" id="article_{{ i }}">
            <div class="col-md-9">
                <h2>{{ "Contact"|trans }}</h2>
                <section class="text-shadow mb-2">
                    <div><b>{{ 'Phone'|trans }}</b>: <span class="phone-number">{{ "show"|trans }}</span></div>
                    <div><b>Email</b>: <a href="mailto:{{ email }}">{{ email }}</a></div>
                    <div><b>{{ 'Address'|trans }}</b>: {{ address }}</div>
                </section>
            </div>
            <div class="col-md-3 contact">
                <a class="btn btn-success ml-auto w-100 d-block" href="{{ url('contact') }}">{{ "Contact"|trans }}</a>
            </div>
        </article>
    </div>

    <section class="py-4 px-3 background-section" id="offer">
        <h2 class="text-center mb-4">{{ "Example realization"|trans }}</h2>
        {% for realization in realizations %}
            <div class="row mt-4">
                <div class="col-md-3 col-sm-12 realization">
                    <a href="{{ realization.url }}" target="_blank">
                        {% if realization.fullFileFn %}
                            <img src="{{ asset(realization.fullFileFn) }}" class="mb-2 mx-auto d-block max-width-100p"
                                 alt="{{ realization.title }}">
                            <span class="text-center d-block fw-bolder">{{ realization.title }}</span>
                        {% endif %}
                    </a>
                </div>
                <div class="col-md-9 col-sm-12 offer">
                    {{ realization.translate(locale).description|raw }}
                </div>
            </div>
        {% endfor %}
    </section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('homepage') }}
{% endblock %}

templates/website/not-access.html.twig
{% extends 'website/base.html.twig' %}

{% block content %}
    <div class="p-5">
        <h1>{{ "No access for this page"|trans }}.</h1>
    </div>
{% endblock %}